title: Salwa Iska
description: Website pribadi Salwa Iska
baseurl: "" 
url: "https://salwaiska027.github.io"

theme: minima

author:
  name: Salwa Iska
  email: salwalsm559@gmail.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
